APP_TITLE = "An Optimal Samples Selection System"
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 760
WINDOW_MIN_WIDTH = 1180
WINDOW_MIN_HEIGHT = 700

DATABASE_DIR = "database"
DATABASE_FILE = "results.db"

DEFAULT_SEED = 42
DEFAULT_ATTEMPTS = 3
DEFAULT_MAX_CANDIDATES = 200000